### ISSUE TITLE
USER STORY: Pinned restaurants/Restaurants to visit

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#11]
Epic #4 

As a **User** I want to **pin a restaurant** so that **I can see the restaurants i want to visit in my profile**.

** Acceptance Criteria **

- [x] User should be able to pin a restaurant when viewing all the restaurants after clicking on a category
- [x] User should be able to see all pinned restaurants in their profile

** Tasks **

- [x] Add section in Profile template that allows user to see pinned restaurants if user has pinned restaurants before 
- [x] Add pin icon as a link in template that renders all the restaurants so that the pin appears with each restaurant. 
- [x] Add function in restaurants views.py that allows the pinned restaurants to be added to user's profile.
- [x] Show messages that shows user that they have pinned a restaurant and or unpinned a restaurant.
- [x] Style buttons to pin restaurants with accordance to website design.
