### ISSUE TITLE
USER STORY: Rate and Review restaurants

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#12]
Epic #5 

As a **User** I want to **rate and review restaurants** so that **I can share my experience after visiting restaurant**

** Acceptance Criteria **

- [x] User should be able to rate out of 5 stars
- [x] User should be able to rate according to criteria such as taste, ambience, customer service, value for money and location
- [x] User should be able to leave a review comment for each restaurant.
- [x] User should only be able to rate if they have signed up and logged in.

** Tasks **

- [x] Create reviews app
- [x] Add app in settings.py
- [x] create urls for review template
- [x] Add review models that has fields taste, ambience, customer service, value for money , location and comment
- [x] Add function in views.py that allows user to rate each restaurant when clicking on rate button next to restaurant that they can see. 
- [x] Add a button in template that allows user to rate for each restaurant 
- [x] Add styling that matches the rest of the website
