### ISSUE TITLE
USER STORY: Seach functionality

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#13]
Epic #2

As a **developer** I can **implement search functionality,** so that **user can easily search for restaurants using key words.**

** Acceptance Criteria **

- [x] User should be able to search certain restaurants in dublin using key words.
- [x] User search should only return restaurants in dublin

** Tasks **

- [x] Create search urls.
- [x] Add views for search functionality.
- [x] Add template to render out search results. 
- [x] Style template to match the design of the rest of the website.
