### ISSUE TITLE
USER STORY: Write Readme.md

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#16]
Epic #14 

As a **Developer** I have to **write extensive documentation on the development of my site** so that **other developers can have access to relevant information needed.**

** Acceptance Criteria **

- [x] Readme must have Table of content with links
- [x] Testing.md 
- [x] 5 Planes of UX in depth.
- [x] No Broken links
- [x] All features, bugs recorded
- [x] Deployment instructions
- [x] All credits, codes taken explained.

** Tasks **

- [x] Write table of content with no broken links
- [x] Link Testing.md to seperate page with clear heading for each testing done.
- [x] Explain how agile methology was implemented
- [x] Show features and bugs with media and in writing
- [x] Have links to add technologies used in project
