### ISSUE TITLE
USER STORY: Pagination

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#17]
Epic #4

As a **User** I can **click the next page button** so that **that one page is not overflowing with results.**

** Acceptance Criteria **

- [x] User should be able to click on next and previous buttons when google api renders out restaurant information if page has more than 8 restaurants.

** Tasks **

- [x] Add pagination in search functionality view and restaurants category view. 
- [x] Implement bootstrap pagination classes
- [x] Style pagination buttons to match the rest of the website.
