### ISSUE TITLE
USER STORY: Profile

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#19]
Epic #6

As a **User** I can **see my profile** so that **i can update information about myself, see or delete reviews already made, and see all the pinned restaurants i want to go visit **

**Acceptance Criteria**

- [x] User should have a profile as soon as they sign up.
- [x] User should be able to update their profile whenever they want to.
- [x] User should be able to view all reviews made by them in their profile page
- [x] User should be able to see all the restaurants they pinned as restaurants that they want to visit in the future.

**Tasks**

- [x] Create profile template that allows user to see their profile 
- [x] Create edit profile template that allows user to update their details. 
- [x] add urls for profile and editprofile templates
- [x] Add profile model that takes in users name, surname, about , favourite food ,saves pinned restaurants, saves all reviews made by user 
- [x] add fxns in forms.py that takes in the model fields.
- [x] Add links to edit reviews, and pinned restaurants.
- [x] Style profile that matches with the design of the entire website.
- [x] Add function in views.py to render profile page, and to allow user to edit their profile.
