### ISSUE TITLE
USER STORY: Restaurant Categories

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#20]
Epic #4

As a **User** I can **can choose restaurants according to categories** so that **that i can view all the restaurants that is available in Dublin according to that category.**

**Acceptance Criteria**

- [x] Each category should render a page with all the restaurants in that category located in Dublin
- [x] The page should render out each restaurant with their name , an image, its website and an address
- [x] Each restaurant must be shown in user in the same format
- [x] User should be able to view websites.
- [x] User should be able to view all reviews of that restaurant
- [x] User  should be able to rate each restaurant after logging in.
- [x] User should be able to pin restaurants they want to visit in the future after logging in.

**Tasks**

- [x] Create Restaurants App
- [x] Add app in settings
- [x] Implement google places API
- [x] Get google places url according to categories.
- [x] Find each restaurant id using places.id of data retrieved from API
- [x] Add function in restaurants.views.py to retrieve necessary data from API
- [x] Add urls for each category of restaurants in the app.urls.
- [x] Style the category page to match with the website design
