### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#21]
Epic #2 

As a **User** I can **use header with navigation bar and footer ** so that **i can find all the necessary information i am looking for with ease in every page of the website**

**Acceptance Criteria**

- [x] Header must have Name of website
- [x] Should have navigation links
- [x] All links should work and not be broken.
- [x] Navigation should be seen in each page of the website
- [x] User should only be shown login tab if they havnt logged in yet
- [x] Useer should only be shown logout tab if they havnt logged out yet
- [x] Profile tab should only shown to users who has signed up or logged in.

**Tasks**

- [x] Create base.html to write all html code that will be repeated for each template.(header and footer)
- [x] Add links to stylesheet, bootstrap, js file.
- [x] Implement template rendering for all templates.
- [x] Implement urls and links to all a tags in base.html
- [x]  Implement Load static
- [x] Style navbar with the design of the website.
