### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#22]
Epic: #2 

As a **User** I can **see home page of website** so that **so that i can immediately know what the website is about and can see how to navigate to other pages**

**Acceptance Criteria**

- [x] Home page should show header with navigation links
- [x] Should have a hero image that shows more information about the website 
- [x] Should have link to socials in footer 
- [x] Should have search functionality in home page

**Tasks**

- [x] Create home app in project
- [x] Add app in settings.py 
- [x] Add urls for home page so that the first page user sees is the home page
- [x] Add style to go with the color scheme of the entire website
- [x] Add template that renders out home page. 
- [x] Include search functionality html,css in home page
