### ISSUE TITLE
USER STORY: Login /out

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#23]
Epic #3 

As a **User** I want to **Login and Logout** so that I can use the **features available to registered users.**

**Acceptance Criteria**

- [x] User must be able to log in only once they have signed up.
- [x] User should be redirected to log in if they want to access features.
- [x] User shouldn't see the login tab after they have logged in already.
- [x] User shouldn't see logout tab if they have logged out already
- [x] User should only be able to access restaurant website, reviews, be able to rate and pin restaurant after logging in

**Tasks**

- [x] Update  settings.
- [x] Add and link urls for djangoallauth login, logout
- [x] Add and update templates.
- [x] Style templates to match site .
- [x] Implement if user.isauthenticated for features 
- [x] Use @Loginrequired feature for functionality
