### ISSUE TITLE
USER STORY: Sign up/Register

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#24]
Epic #3 

As a **User** I want to **sign up / register once** so that **i can have access to all features available on site**

**Acceptance Criteria**

- [x] User should be able to sign up using a form when clicking on signup tab in navbar.
- [x] User should have access to sign up in log in form incase they dont have an account yet. 
- [x] User should only be able to log in after sign up
- [x] Sign up tab should disappear once signed up once.

**Tasks**

- [x] Install django allauth
- [x] Update settings
- [x] Add urls 
- [x] Add and update templates
- [x] Style templates to match site
