### ISSUE TITLE
USER STORY: Testing

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#25]
Epic #14 

As a **Developer** I have to **test website extensively* so that **there would be no code, logical, accessibility errors **

***Acceptance Criteria***

- [x] No errors should pop up while user uses site.
- [x] Any errors should lead user to relevant error pages.
- [x] All testing documented in ReadMe.
- [x] Some automated testing and all manual testing should be done. 

***Tasks***

- [x] Implement Validator testing for html, css, python, js.
- [x] Carry out manual testing and document in readme.
- [x] Implement some unit testing. 
- [x] Carry out Lighthouse testing.
- [x] Carry out Accessibility testing.
