### ISSUE TITLE
USER STORY: Delete review/rating

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#30]
Epic #5 

As a **user** I can **delete a review I made** so that **create a new one in the future.**

** Acceptance Criteria **

- [x] User should be able to delete review whenever they want.
- [x] User should be asked twice if they want delete rating to confirm their action. 
- [x] Only authenticated users or superuser are allowed to delete reviews

** Tasks **

- [x] Create delete review view
- [x] Add urls for deleting review
- [x] Add bootstrap pop modal to confirm deletion
- [x] Add the necessary html and for delete review functionality
- [x] Style the delete html with accordance with the entire website.
