### ISSUE TITLE
USER STORY: delete reviews/profiles

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#31]
Epic #3

As a **site admin** i can **review comments left for restaurant reviews** so that **i can filter out any offensive language.**

** Acceptance Criteria **

- [x] Admin user/superuser should be able to delete reviews or profiles of any users that have signed up with the website.

** Tasks **

- [x] Implement functionality for super users for edit review.
- [x] Implement functionality for superusers for edit profile.
