### ISSUE TITLE
USER STORY: Delete Profile

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#32]
Epic #6 

As a **user** i can **delete profile** so that **remove my account from the website.**

** Acceptance Criteria **

- [x] User should be able to delete profile whenever they want.
- [x] User should be asked twice if they want delete profile to confirm their action. 
- [x] Only authenticated users or superuser are allowed to delete profile.
- [x] When user deletes profile their account should be deleted, and would have to signup again.

** Tasks **

- [x] Create delete profile view
- [x] Add urls for deleting profile
- [x] Add bootstrap pop modal to confirm deletion
- [x] Add the necessary html and for delete profile functionality
- [x] Style the delete html with accordance with the entire website.
