### ISSUE TITLE
USER STORY: Email verification

### ISSUE THREAD

**Issue by SooryaGeorge7** [SooryaGeorge7/Dublin-Eats#34]
As a **user** i can **signup with email verification** so that **noone else would be able to signup using my email.**

** Acceptance Criteria **

- [ ] Users are able verify their email when signing up

** Tasks **

 - [ ] Update email settings in settings.py
 - [ ]  style templates to match website design
